/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./app/**/*.{js,ts,jsx,tsx,mdx}",
      "./pages/**/*.{js,ts,jsx,tsx,mdx}",
      "./components/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/**/*.{js,ts,jsx,tsx,mdx}",
      "./index.html",
    ],
    theme: {
        extend: {
            colors: {
                "surface-container-high": "#292a2b",
                "on-primary": "#1000a9",
                "background": "#121315",
                "secondary-fixed-dim": "#c4c6cc",
                "inverse-primary": "#494bd6",
                "surface-container-highest": "#343536",
                "on-secondary-fixed-variant": "#44474c",
                "on-error-container": "#ffdad6",
                "inverse-surface": "#e3e2e3",
                "secondary-fixed": "#e1e2e8",
                "surface-container-lowest": "#0d0e0f",
                "tertiary-fixed": "#ffdad7",
                "error": "#ffb4ab",
                "surface-bright": "#38393a",
                "on-primary-fixed-variant": "#2f2ebe",
                "surface": "#121315",
                "primary": "#c0c1ff",
                "on-tertiary-fixed": "#410005",
                "on-secondary-fixed": "#191c20",
                "on-surface": "#e3e2e3",
                "on-surface-variant": "#c7c4d7",
                "surface-dim": "#121315",
                "primary-container": "#8083ff",
                "tertiary-container": "#f55e5d",
                "on-tertiary-fixed-variant": "#8e101c",
                "error-container": "#93000a",
                "primary-fixed-dim": "#c0c1ff",
                "outline-variant": "#464554",
                "outline": "#908fa0",
                "on-tertiary-container": "#5c000b",
                "surface-tint": "#c0c1ff",
                "surface-variant": "#343536",
                "inverse-on-surface": "#303032",
                "tertiary": "#ffb3af",
                "on-secondary": "#2e3135",
                "on-primary-container": "#0d0096",
                "tertiary-fixed-dim": "#ffb3af",
                "on-secondary-container": "#b6b8be",
                "primary-fixed": "#e1e0ff",
                "surface-container": "#1f2021",
                "secondary": "#c4c6cc",
                "surface-container-low": "#1b1c1d",
                "on-error": "#690005",
                "on-tertiary": "#68000e",
                "secondary-container": "#46494e",
                "on-primary-fixed": "#07006c",
                "on-background": "#e3e2e3"
            },
            fontFamily: {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "mono": ["Berkeley Mono", "monospace"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
